openapi: 3.0.0
info:
  title: Payments API
  description: API cho module payments
  version: 1.0.0
  contact:
    name: API Support
    email: api@example.com
servers:
- url: https://api.example.com/api/v1
  description: Production server
- url: https://staging-api.example.com/api/v1
  description: Staging server
tags:
- name: payments
  description: Operations related to payments
paths:
  /payments:
    get:
      tags:
      - payments
      summary: List all payments
      description: Returns a list of payments
      operationId: listPayments
      parameters:
      - name: page
        in: query
        description: Page number
        required: false
        schema:
          type: integer
          default: 1
      - name: page_size
        in: query
        description: Number of items per page
        required: false
        schema:
          type: integer
          default: 10
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  status_code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: List of payments
                  data:
                    type: array
                    items:
                      type: object
                  pagination:
                    type: object
                    properties:
                      count:
                        type: integer
                      page_size:
                        type: integer
                      current_page:
                        type: integer
                      total_pages:
                        type: integer
                      next:
                        type: string
                        nullable: true
                      previous:
                        type: string
                        nullable: true
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  status_code:
                    type: integer
                    example: 401
                  message:
                    type: string
                    example: Authentication credentials were not provided.
      security:
      - BearerAuth: []
    post:
      tags:
      - payments
      summary: Create a new payment
      description: Creates a new payment and returns its details
      operationId: createPayment
      requestBody:
        description: Payment object that needs to be created
        content:
          application/json:
            schema:
              type: object
        required: true
      responses:
        '201':
          description: Created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  status_code:
                    type: integer
                    example: 201
                  message:
                    type: string
                    example: Payment created successfully
                  data:
                    type: object
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  status_code:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: Invalid input
                  errors:
                    type: object
      security:
      - BearerAuth: []
  /payments/{id}:
    get:
      tags:
      - payments
      summary: Get payment by ID
      description: Returns a single payment
      operationId: getPayment
      parameters:
      - name: id
        in: path
        description: ID of payment to return
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  status_code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Payment details
                  data:
                    type: object
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  status_code:
                    type: integer
                    example: 404
                  message:
                    type: string
                    example: Payment not found
      security:
      - BearerAuth: []
    put:
      tags:
      - payments
      summary: Update payment
      description: Updates an existing payment
      operationId: updatePayment
      parameters:
      - name: id
        in: path
        description: ID of payment to update
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        description: Payment object that needs to be updated
        content:
          application/json:
            schema:
              type: object
        required: true
      responses:
        '200':
          description: Updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  status_code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Payment updated successfully
                  data:
                    type: object
      security:
      - BearerAuth: []
    delete:
      tags:
      - payments
      summary: Delete payment
      description: Deletes a payment
      operationId: deletePayment
      parameters:
      - name: id
        in: path
        description: ID of payment to delete
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '204':
          description: Deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  status_code:
                    type: integer
                    example: 204
                  message:
                    type: string
                    example: Payment deleted successfully
      security:
      - BearerAuth: []
components:
  schemas: {}
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
