# Generated by Django 5.1.7 on 2025-06-01 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_is_customer_alter_user_is_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertoken",
            name="user",
        ),
        migrations.DeleteModel(
            name="LoginHistory",
        ),
        migrations.DeleteModel(
            name="UserToken",
        ),
    ]
