# Generated by Django 5.2 on 2025-04-05 13:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Banner Image')),
                ('link_url', models.URLField(blank=True, verbose_name='Link URL')),
                ('position', models.CharField(choices=[('homepage_top', 'Homepage Top'), ('homepage_middle', 'Homepage Middle'), ('homepage_bottom', 'Homepage Bottom'), ('footer', 'Footer'), ('sidebar', 'Sidebar'), ('category_page', 'Category Page'), ('product_page', 'Product Page')], max_length=30, verbose_name='Position')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL Slug')),
                ('content_html', models.TextField(verbose_name='HTML Content')),
                ('content_text', models.TextField(blank=True, help_text='Plain text version for SEO and accessibility', verbose_name='Text Content')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('seo_title', models.CharField(blank=True, help_text='SEO optimized title (max 70 characters)', max_length=70, verbose_name='SEO Title')),
                ('seo_description', models.CharField(blank=True, help_text='Meta description for SEO (max 160 characters)', max_length=160, verbose_name='SEO Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
                ('url', models.CharField(help_text='URL path or absolute link', max_length=255, verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('menu_type', models.CharField(choices=[('header', 'Header Menu'), ('footer', 'Footer Menu'), ('mobile', 'Mobile Menu'), ('sidebar', 'Sidebar Menu'), ('account', 'Account Menu')], max_length=20, verbose_name='Menu Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pages.menuitem', verbose_name='Parent Menu Item')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['menu_type', 'order'],
            },
        ),
    ]
