# Generated by Django 5.1.7 on 2025-04-13 12:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Department Code"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_departments",
                        to="hrm.department",
                        verbose_name="Parent Department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Employee ID"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="Last Name"),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                        verbose_name="Gender",
                    ),
                ),
                ("email", models.EmailField(max_length=255, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Phone Number"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Address")),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Emergency Contact Name",
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Emergency Contact Phone",
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("intern", "Intern"),
                            ("probation", "Probation"),
                            ("terminated", "Terminated"),
                        ],
                        default="full_time",
                        max_length=20,
                        verbose_name="Employment Status",
                    ),
                ),
                ("hire_date", models.DateField(verbose_name="Hire Date")),
                (
                    "termination_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Termination Date"
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="employees/profile_pictures/",
                        verbose_name="Profile Picture",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="hrm.department",
                        verbose_name="Department",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subordinates",
                        to="hrm.employee",
                        verbose_name="Supervisor",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.AddField(
            model_name="department",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_department",
                to="hrm.employee",
                verbose_name="Department Manager",
            ),
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("annual", "Annual Leave"),
                            ("sick", "Sick Leave"),
                            ("maternity", "Maternity Leave"),
                            ("paternity", "Paternity Leave"),
                            ("bereavement", "Bereavement Leave"),
                            ("unpaid", "Unpaid Leave"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Leave Type",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
                (
                    "half_day",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, this leave request is for half a day",
                        verbose_name="Half Day",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="Reason")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reviewed At"
                    ),
                ),
                (
                    "reviewer_comments",
                    models.TextField(blank=True, verbose_name="Reviewer Comments"),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Supporting documents (e.g., medical certificate)",
                        null=True,
                        upload_to="leave_requests/attachments/",
                        verbose_name="Attachment",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="hrm.employee",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_leave_requests",
                        to="hrm.employee",
                        verbose_name="Reviewed By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Request",
                "verbose_name_plural": "Leave Requests",
                "ordering": ["-start_date", "status"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Position Code"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "requirements",
                    models.TextField(blank=True, verbose_name="Requirements"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "min_salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Minimum Salary",
                    ),
                ),
                (
                    "max_salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Maximum Salary",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="hrm.department",
                        verbose_name="Department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Position",
                "verbose_name_plural": "Positions",
                "ordering": ["title"],
                "unique_together": {("title", "department")},
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="position",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="hrm.position",
                verbose_name="Position",
            ),
        ),
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salary_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("hourly", "Hourly"),
                            ("commission", "Commission"),
                        ],
                        default="monthly",
                        max_length=20,
                        verbose_name="Salary Type",
                    ),
                ),
                (
                    "base_salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Base Salary"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("VND", "Vietnamese Dong"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                        ],
                        default="VND",
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "allowances",
                    models.JSONField(
                        default=dict,
                        help_text='Additional allowances as key-value pairs (e.g., {"transportation": 500000})',
                        verbose_name="Allowances",
                    ),
                ),
                (
                    "deductions",
                    models.JSONField(
                        default=dict,
                        help_text='Standard deductions as key-value pairs (e.g., {"tax": 150000})',
                        verbose_name="Deductions",
                    ),
                ),
                ("effective_date", models.DateField(verbose_name="Effective Date")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salaries",
                        to="hrm.employee",
                        verbose_name="Employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Salary",
                "verbose_name_plural": "Salaries",
                "ordering": ["-effective_date"],
                "unique_together": {("employee", "effective_date")},
            },
        ),
        migrations.CreateModel(
            name="WorkSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Schedule Name"),
                ),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular"),
                            ("shift", "Shift"),
                            ("flexible", "Flexible"),
                        ],
                        default="regular",
                        max_length=20,
                        verbose_name="Schedule Type",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Start Time")),
                ("end_time", models.TimeField(verbose_name="End Time")),
                (
                    "working_days",
                    models.JSONField(
                        default=list,
                        help_text="Days of the week when this schedule applies",
                        verbose_name="Working Days",
                    ),
                ),
                (
                    "break_duration",
                    models.PositiveIntegerField(
                        default=60,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(240),
                        ],
                        verbose_name="Break Duration (minutes)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("effective_date", models.DateField(verbose_name="Effective Date")),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Expiration Date"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_schedules",
                        to="hrm.department",
                        verbose_name="Department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Schedule",
                "verbose_name_plural": "Work Schedules",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Holiday Name")),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "holiday_type",
                    models.CharField(
                        choices=[
                            ("public", "Public Holiday"),
                            ("company", "Company Holiday"),
                        ],
                        default="public",
                        max_length=20,
                        verbose_name="Holiday Type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=True, verbose_name="Paid Holiday"),
                ),
                (
                    "recurring",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, this holiday repeats every year on the same date",
                        verbose_name="Recurring Yearly",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "applicable_departments",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Leave empty if applies to all departments",
                        related_name="holidays",
                        to="hrm.department",
                        verbose_name="Applicable Departments",
                    ),
                ),
            ],
            options={
                "verbose_name": "Holiday",
                "verbose_name_plural": "Holidays",
                "ordering": ["date"],
                "unique_together": {("name", "date")},
            },
        ),
        migrations.CreateModel(
            name="Payroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payroll_period",
                    models.CharField(max_length=50, verbose_name="Payroll Period"),
                ),
                ("start_date", models.DateField(verbose_name="Period Start Date")),
                ("end_date", models.DateField(verbose_name="Period End Date")),
                (
                    "gross_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Gross Amount"
                    ),
                ),
                (
                    "deductions",
                    models.JSONField(
                        default=dict,
                        help_text='All deductions as key-value pairs (e.g., {"tax": 150000, "insurance": 100000})',
                        verbose_name="Deductions",
                    ),
                ),
                (
                    "allowances",
                    models.JSONField(
                        default=dict,
                        help_text='All allowances as key-value pairs (e.g., {"overtime": 200000, "bonus": 500000})',
                        verbose_name="Allowances",
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Net Amount"
                    ),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="Overtime Hours",
                    ),
                ),
                (
                    "overtime_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.5,
                        max_digits=5,
                        verbose_name="Overtime Rate",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Payment Date"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("bank_transfer", "Bank Transfer"),
                            ("cash", "Cash"),
                            ("check", "Check"),
                        ],
                        default="bank_transfer",
                        max_length=20,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Payment Reference"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("processed", "Processed"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved At"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_payrolls",
                        to="hrm.employee",
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payrolls",
                        to="hrm.employee",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "salary",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payrolls",
                        to="hrm.salary",
                        verbose_name="Salary Structure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll",
                "verbose_name_plural": "Payrolls",
                "ordering": ["-payroll_period", "employee"],
                "unique_together": {("employee", "payroll_period")},
            },
        ),
        migrations.CreateModel(
            name="Timesheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date"
                    ),
                ),
                ("check_in", models.DateTimeField(verbose_name="Check In Time")),
                (
                    "check_out",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Check Out Time"
                    ),
                ),
                (
                    "break_duration",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Break Duration (minutes)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved At"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_timesheets",
                        to="hrm.employee",
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheets",
                        to="hrm.employee",
                        verbose_name="Employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timesheet",
                "verbose_name_plural": "Timesheets",
                "ordering": ["-date", "-check_in"],
                "unique_together": {("employee", "date", "check_in")},
            },
        ),
    ]
