# Generated by Django 5.1.7 on 2025-06-01 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timesheet",
            name="date",
            field=models.DateField(default=datetime.date.today, verbose_name="Date"),
        ),
    ]
