# Generated by Django 5.2 on 2025-04-05 13:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Currency Code')),
                ('name', models.CharField(max_length=100, verbose_name='Currency Name')),
                ('symbol', models.CharField(max_length=5, verbose_name='Currency Symbol')),
                ('exchange_rate_to_base', models.DecimalField(decimal_places=6, default=1.0, max_digits=10, verbose_name='Exchange Rate to Base Currency')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default Currency')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['-is_default', 'code'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.CharField(max_length=100, unique=True, verbose_name='Template Key')),
                ('subject', models.CharField(max_length=255, verbose_name='Email Subject')),
                ('body_html', models.TextField(verbose_name='HTML Body')),
                ('body_text', models.TextField(verbose_name='Text Body')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['template_key'],
            },
        ),
        migrations.CreateModel(
            name='LanguageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Language Code')),
                ('name', models.CharField(max_length=100, verbose_name='Language Name')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default Language')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Language Setting',
                'verbose_name_plural': 'Language Settings',
                'ordering': ['-is_default', 'code'],
            },
        ),
        migrations.CreateModel(
            name='StoreSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255, verbose_name='Store Name')),
                ('store_logo', models.ImageField(blank=True, null=True, upload_to='store/logo/', verbose_name='Store Logo')),
                ('support_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Support Email')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('is_maintenance_mode', models.BooleanField(default=False, verbose_name='Maintenance Mode')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_settings', to='settings.currency', verbose_name='Default Currency')),
                ('default_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_settings', to='settings.languagesetting', verbose_name='Default Language')),
            ],
            options={
                'verbose_name': 'Store Setting',
                'verbose_name_plural': 'Store Settings',
            },
        ),
    ]
