# Generated by Django 5.2 on 2025-04-05 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Total Orders')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Revenue')),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Discount')),
                ('net_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Net Revenue')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sales Report',
                'verbose_name_plural': 'Sales Reports',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TrafficLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255, verbose_name='Endpoint')),
                ('method', models.CharField(max_length=10, verbose_name='HTTP Method')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('duration_ms', models.PositiveIntegerField(verbose_name='Duration (ms)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
            ],
            options={
                'verbose_name': 'Traffic Log',
                'verbose_name_plural': 'Traffic Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CustomerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Total Orders')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Spent')),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Average Order Value')),
                ('last_order_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Order At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='customers.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Customer Report',
                'verbose_name_plural': 'Customer Reports',
                'ordering': ['-total_spent'],
            },
        ),
        migrations.CreateModel(
            name='ProductReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_quantity', models.PositiveIntegerField(default=0, verbose_name='Sold Quantity')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Revenue')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Average Rating')),
                ('last_sold_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Sold At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Report',
                'verbose_name_plural': 'Product Reports',
                'ordering': ['-sold_quantity'],
            },
        ),
    ]
