# Generated by Django 5.1.7 on 2025-05-13 14:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Workflow Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Version"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="The model this workflow can be applied to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Target Model",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_workflows",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow",
                "verbose_name_plural": "Workflows",
                "ordering": ["-updated_at"],
                "unique_together": {("name", "version")},
            },
        ),
        migrations.CreateModel(
            name="WorkflowConditionContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Context Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "variables",
                    models.JSONField(
                        default=dict,
                        help_text="JSON mapping of variable names to source paths or expressions",
                        verbose_name="Variables",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="condition_contexts",
                        to="workflow.workflow",
                        verbose_name="Workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Condition Context",
                "verbose_name_plural": "Workflow Condition Contexts",
            },
        ),
        migrations.CreateModel(
            name="WorkflowStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Step Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("order", models.PositiveIntegerField(default=1, verbose_name="Order")),
                (
                    "is_start",
                    models.BooleanField(default=False, verbose_name="Is Start Step"),
                ),
                (
                    "is_end",
                    models.BooleanField(default=False, verbose_name="Is End Step"),
                ),
                (
                    "wait_all",
                    models.BooleanField(
                        default=False,
                        help_text="If True, all parallel steps must complete before proceeding",
                        verbose_name="Wait for All Parallel Steps",
                    ),
                ),
                (
                    "wait_any",
                    models.BooleanField(
                        default=False,
                        help_text="If True, only one parallel step needs to complete before proceeding",
                        verbose_name="Wait for Any Parallel Step",
                    ),
                ),
                (
                    "auto_proceed",
                    models.BooleanField(
                        default=False,
                        help_text="If True, step will automatically proceed to next step after actions complete",
                        verbose_name="Auto Proceed",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="workflow.workflow",
                        verbose_name="Workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Step",
                "verbose_name_plural": "Workflow Steps",
                "ordering": ["workflow", "order"],
                "unique_together": {("workflow", "order")},
            },
        ),
        migrations.CreateModel(
            name="WorkflowInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("terminated", "Terminated"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict,
                        help_text="Additional data stored during workflow execution",
                        verbose_name="Instance Data",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_workflow_instances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "current_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_workflow_instances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Current User",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="workflow.workflow",
                        verbose_name="Workflow",
                    ),
                ),
                (
                    "current_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_instances",
                        to="workflow.workflowstep",
                        verbose_name="Current Step",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Instance",
                "verbose_name_plural": "Workflow Instances",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowActorConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("user", "Specific User"),
                            ("group", "User Group"),
                            ("role", "User Role"),
                            ("dynamic", "Dynamic Expression"),
                        ],
                        max_length=20,
                        verbose_name="Actor Type",
                    ),
                ),
                (
                    "role_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Role Name"
                    ),
                ),
                (
                    "dynamic_expression",
                    models.TextField(
                        blank=True,
                        help_text="Python expression to dynamically determine the actor",
                        verbose_name="Dynamic Expression",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.group",
                        verbose_name="Group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "workflow_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actor_configs",
                        to="workflow.workflowstep",
                        verbose_name="Workflow Step",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Actor Configuration",
                "verbose_name_plural": "Workflow Actor Configurations",
            },
        ),
        migrations.CreateModel(
            name="WorkflowAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Action Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("email", "Send Email"),
                            ("api", "Call API"),
                            ("update", "Update Record"),
                            ("function", "Call Function"),
                            ("notification", "Send Notification"),
                        ],
                        max_length=20,
                        verbose_name="Action Type",
                    ),
                ),
                (
                    "trigger_point",
                    models.CharField(
                        choices=[
                            ("on_enter", "On Step Enter"),
                            ("on_exit", "On Step Exit"),
                            ("on_complete", "On Step Complete"),
                            ("on_reject", "On Step Reject"),
                        ],
                        max_length=20,
                        verbose_name="Trigger Point",
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        default=dict,
                        help_text="JSON configuration specific to the action type",
                        verbose_name="Configuration",
                    ),
                ),
                (
                    "is_async",
                    models.BooleanField(
                        default=False,
                        help_text="If True, action will be executed asynchronously",
                        verbose_name="Asynchronous",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Execution Order"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "workflow_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="workflow.workflowstep",
                        verbose_name="Workflow Step",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Action",
                "verbose_name_plural": "Workflow Actions",
                "ordering": ["workflow_step", "trigger_point", "order"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowStepLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=50, verbose_name="Action")),
                (
                    "performed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Performed At"
                    ),
                ),
                ("data", models.JSONField(default=dict, verbose_name="Action Data")),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Performed By",
                    ),
                ),
                (
                    "workflow_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="workflow.workflowinstance",
                        verbose_name="Workflow Instance",
                    ),
                ),
                (
                    "workflow_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="workflow.workflowstep",
                        verbose_name="Workflow Step",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Step Log",
                "verbose_name_plural": "Workflow Step Logs",
                "ordering": ["-performed_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Transition Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "condition_expression",
                    models.TextField(
                        blank=True,
                        help_text="Python-safe expression that must evaluate to True for this transition to be valid",
                        verbose_name="Condition Expression",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="When multiple transitions are valid, higher priority transitions are chosen first",
                        verbose_name="Priority",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "source_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_transitions",
                        to="workflow.workflowstep",
                        verbose_name="Source Step",
                    ),
                ),
                (
                    "target_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_transitions",
                        to="workflow.workflowstep",
                        verbose_name="Target Step",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Transition",
                "verbose_name_plural": "Workflow Transitions",
                "ordering": ["-priority"],
            },
        ),
        migrations.AddIndex(
            model_name="workflowinstance",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="workflow_wo_content_5cb705_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowinstance",
            index=models.Index(fields=["status"], name="workflow_wo_status_665f9a_idx"),
        ),
        migrations.AddIndex(
            model_name="workflowsteplog",
            index=models.Index(
                fields=["workflow_instance", "performed_at"],
                name="workflow_wo_workflo_482d26_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowsteplog",
            index=models.Index(
                fields=["performed_by"], name="workflow_wo_perform_2cff81_idx"
            ),
        ),
    ]
