# Generated by Django 5.2 on 2025-04-05 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Method Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('estimated_days', models.PositiveIntegerField(default=3, verbose_name='Estimated Delivery Days')),
                ('base_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Base Fee')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Shipping Method',
                'verbose_name_plural': 'Shipping Methods',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Zone Name')),
                ('countries', models.TextField(help_text="Comma-separated list of country codes (e.g. 'VN,TH,SG')", verbose_name='Countries')),
                ('provinces', models.TextField(blank=True, help_text='Comma-separated list of provinces/states (can be empty)', verbose_name='Provinces/States')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Shipping Zone',
                'verbose_name_plural': 'Shipping Zones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(blank=True, max_length=100, verbose_name='Tracking Code')),
                ('shipment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Shipment Status')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Shipped At')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered At')),
                ('shipping_address', models.TextField(blank=True, verbose_name='Shipping Address')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order', verbose_name='Order')),
                ('shipping_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='shipping.shippingmethod', verbose_name='Shipping Method')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_info', to='shipping.shipment', verbose_name='Shipment')),
            ],
            options={
                'verbose_name': 'Tracking Information',
                'verbose_name_plural': 'Tracking Information',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_weight', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Minimum Weight (kg)')),
                ('max_weight', models.DecimalField(decimal_places=2, default=999, max_digits=8, verbose_name='Maximum Weight (kg)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('currency', models.CharField(default='VND', max_length=3, verbose_name='Currency')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('shipping_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='shipping.shippingmethod', verbose_name='Shipping Method')),
                ('shipping_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='shipping.shippingzone', verbose_name='Shipping Zone')),
            ],
            options={
                'verbose_name': 'Shipping Rate',
                'verbose_name_plural': 'Shipping Rates',
                'ordering': ['shipping_method', 'shipping_zone', 'min_weight'],
                'unique_together': {('shipping_method', 'shipping_zone', 'min_weight', 'max_weight')},
            },
        ),
    ]
