# Generated by Django 5.1.7 on 2025-04-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_product_category_product_category_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="seller_id",
        ),
    ]
