# Generated by Django 5.1.7 on 2025-04-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_rename_category_id_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=2550),
        ),
    ]
