# Generated by Django 5.1.7 on 2025-04-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="alt_text",
            field=models.CharField(blank=True, max_length=2550),
        ),
    ]
