# Generated by Django 5.1.7 on 2025-04-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_productimage_alt_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.CharField(),
        ),
    ]
